package com.librium.subtitle

/**
 * Export serializers. Output preserves as much of the document as the
 * target format supports — notably, ASS export reuses the parsed header,
 * style definitions, and raw dialogue text (override tags included), so
 * styling information is never silently discarded.
 */
fun SubtitleDocument.exportAs(format: SubtitleFormat): String = when (format) {
    SubtitleFormat.SRT -> exportSrt()
    SubtitleFormat.VTT -> exportVtt()
    SubtitleFormat.ASS -> exportAss(ssa = false)
    SubtitleFormat.SSA -> exportAss(ssa = true)
    SubtitleFormat.UNKNOWN -> exportSrt()
}

fun SubtitleDocument.exportSrt(): String {
    val out = StringBuilder()
    events.forEachIndexed { number, event ->
        if (number > 0) out.append('\n')
        out.append(number + 1).append('\n')
        out.append(formatSrtTimestamp(event.startMs))
        out.append(" --> ")
        out.append(formatSrtTimestamp(event.endMs)).append('\n')
        out.append(event.text).append('\n')
    }
    return out.toString()
}

fun SubtitleDocument.exportVtt(): String {
    val out = StringBuilder("WEBVTT")
    val header = rawHeader?.trim()
    if (!header.isNullOrEmpty()) {
        out.append('\n').append('\n').append(header)
    }
    for (event in events) {
        out.append('\n').append('\n')
        if (!event.identifier.isNullOrBlank()) out.append(event.identifier.trim()).append('\n')
        out.append(formatVttTimestamp(event.startMs))
        out.append(" --> ")
        out.append(formatVttTimestamp(event.endMs))
        if (!event.cueSettings.isNullOrBlank()) out.append(' ').append(event.cueSettings.trim())
        out.append('\n').append(event.text.trim())
    }
    out.append('\n')
    return out.toString()
}

fun SubtitleDocument.exportAss(ssa: Boolean = false): String {
    val out = StringBuilder()
    val header = rawHeader?.trim()
    if (!header.isNullOrEmpty()) {
        out.append(header).append('\n')
    } else {
        out.append(buildAssHeader(ssa)).append('\n')
    }
    out.append('\n').append("[Events]").append('\n')
    val order = eventFormat?.split(",")?.map { it.trim().lowercase() }
        ?: DEFAULT_ASS_EVENT_ORDER
    out.append("Format: ").append(order.joinToString(", ") { displayAssField(it) }).append('\n')
    for (event in events) {
        out.append("Dialogue: ")
        val values = order.map { field ->
            dialogueField(field, event, ssa)
        }
        out.append(values.joinToString(",")).append('\n')
    }
    for (comment in extraSections[ASS_COMMENTS_KEY].orEmpty()) {
        out.append(comment.trim()).append('\n')
    }
    for ((section, lines) in extraSections) {
        if (section == ASS_COMMENTS_KEY || lines.isEmpty()) continue
        out.append('\n').append('[').append(section).append(']').append('\n')
        for (line in lines) out.append(line).append('\n')
    }
    return out.toString()
}

const val ASS_COMMENTS_KEY = "events-comments"

private val DEFAULT_ASS_EVENT_ORDER = listOf(
    "marked", "start", "end", "style", "name",
    "marginl", "marginr", "marginv", "effect", "text",
)

private fun displayAssField(lower: String): String = when (lower) {
    "marked" -> "Marked"
    "start" -> "Start"
    "end" -> "End"
    "style" -> "Style"
    "name" -> "Name"
    "marginl" -> "MarginL"
    "marginr" -> "MarginR"
    "marginv" -> "MarginV"
    "effect" -> "Effect"
    "text" -> "Text"
    else -> lower.replaceFirstChar { it.uppercase() }
}

private fun dialogueField(field: String, event: SubtitleEvent, ssa: Boolean): String {
    when (field) {
        "start" -> return formatAssTimestamp(event.startMs)
        "end" -> return formatAssTimestamp(event.endMs)
        "style" -> return event.styleName ?: "Default"
        "text" -> return event.rawText ?: escapeAssText(event.text)
    }
    event.extra[field]?.let { return it }
    return when (field) {
        "marked" -> if (ssa) "Marked=0" else "0"
        "name" -> ""
        "marginl", "marginr", "marginv" -> "0"
        "effect" -> ""
        else -> ""
    }
}

private fun escapeAssText(text: String): String =
    text.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\\N")

private fun SubtitleDocument.buildAssHeader(ssa: Boolean): String {
    val out = StringBuilder("[Script Info]\n")
    if (metadata.isEmpty()) {
        out.append("; Generated by Librium\n")
        out.append(if (ssa) "ScriptType: v4.00\n" else "ScriptType: v4.00+\n")
    } else {
        for ((key, value) in metadata) out.append(key).append(": ").append(value).append('\n')
    }
    val section = if (ssa) "V4 Styles" else "V4+ Styles"
    out.append('\n').append('[').append(section).append(']').append('\n')
    val order = styleFormat?.split(",")?.map { it.trim().lowercase() }
        ?: DEFAULT_ASS_STYLE_ORDER
    out.append("Format: ").append(order.joinToString(", ") { displayAssField(it) }).append('\n')
    if (styles.isEmpty()) {
        out.append("Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000," +
            "0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n")
    } else {
        for (style in styles.values) {
            val raw = style.rawLine?.trim()
            if (!raw.isNullOrEmpty()) {
                out.append(raw).append('\n')
            } else {
                out.append("Style: ")
                out.append(order.map { field ->
                    when (field) {
                        "name" -> style.name
                        else -> style.fields[field] ?: ""
                    }
                }.joinToString(","))
                out.append('\n')
            }
        }
    }
    return out.toString().trimEnd()
}

private val DEFAULT_ASS_STYLE_ORDER = listOf(
    "name", "fontname", "fontsize", "primarycolour", "secondarycolour",
    "outlinecolour", "backcolour", "bold", "italic", "underline", "strikeout",
    "scalex", "scaley", "spacing", "angle", "borderstyle", "outline",
    "shadow", "alignment", "marginl", "marginr", "marginv", "encoding",
)
